# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: md_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='md_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmd_server.proto\"2\n\nserverInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\":\n\x0eserverInfoList\x12\x0c\n\x04\x64one\x18\x01 \x01(\x05\x12\x1a\n\x05sList\x18\x02 \x03(\x0b\x32\x0b.serverInfo\"\x07\n\x05\x65mpty\"\x18\n\x08ms_reply\x12\x0c\n\x04\x64one\x18\x01 \x01(\x05\x32\xc3\x01\n\tmd_server\x12\x1e\n\x07\x63onnect\x12\x06.empty\x1a\t.ms_reply\"\x00\x12$\n\ndisconnect\x12\t.ms_reply\x1a\t.ms_reply\"\x00\x12\"\n\x06online\x12\x0b.serverInfo\x1a\t.ms_reply\"\x00\x12#\n\x07offline\x12\x0b.serverInfo\x1a\t.ms_reply\"\x00\x12\'\n\nlistServer\x12\x06.empty\x1a\x0f.serverInfoList\"\x00\x62\x06proto3'
)




_SERVERINFO = _descriptor.Descriptor(
  name='serverInfo',
  full_name='serverInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='serverInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='serverInfo.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='serverInfo.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=69,
)


_SERVERINFOLIST = _descriptor.Descriptor(
  name='serverInfoList',
  full_name='serverInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='serverInfoList.done', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sList', full_name='serverInfoList.sList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=129,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=138,
)


_MS_REPLY = _descriptor.Descriptor(
  name='ms_reply',
  full_name='ms_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='ms_reply.done', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=164,
)

_SERVERINFOLIST.fields_by_name['sList'].message_type = _SERVERINFO
DESCRIPTOR.message_types_by_name['serverInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['serverInfoList'] = _SERVERINFOLIST
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ms_reply'] = _MS_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

serverInfo = _reflection.GeneratedProtocolMessageType('serverInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'md_server_pb2'
  # @@protoc_insertion_point(class_scope:serverInfo)
  })
_sym_db.RegisterMessage(serverInfo)

serverInfoList = _reflection.GeneratedProtocolMessageType('serverInfoList', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFOLIST,
  '__module__' : 'md_server_pb2'
  # @@protoc_insertion_point(class_scope:serverInfoList)
  })
_sym_db.RegisterMessage(serverInfoList)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'md_server_pb2'
  # @@protoc_insertion_point(class_scope:empty)
  })
_sym_db.RegisterMessage(empty)

ms_reply = _reflection.GeneratedProtocolMessageType('ms_reply', (_message.Message,), {
  'DESCRIPTOR' : _MS_REPLY,
  '__module__' : 'md_server_pb2'
  # @@protoc_insertion_point(class_scope:ms_reply)
  })
_sym_db.RegisterMessage(ms_reply)



_MD_SERVER = _descriptor.ServiceDescriptor(
  name='md_server',
  full_name='md_server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=167,
  serialized_end=362,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='md_server.connect',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MS_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnect',
    full_name='md_server.disconnect',
    index=1,
    containing_service=None,
    input_type=_MS_REPLY,
    output_type=_MS_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='online',
    full_name='md_server.online',
    index=2,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_MS_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='offline',
    full_name='md_server.offline',
    index=3,
    containing_service=None,
    input_type=_SERVERINFO,
    output_type=_MS_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listServer',
    full_name='md_server.listServer',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVERINFOLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MD_SERVER)

DESCRIPTOR.services_by_name['md_server'] = _MD_SERVER

# @@protoc_insertion_point(module_scope)
