# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topic.proto',
  package='topic',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btopic.proto\x12\x05topic\"\x12\n\x03\x61\x63k\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x05\"E\n\npubMessage\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\x05\x12\x14\n\x0ctimeoutLimit\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"/\n\nsubMessage\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\">\n\x0bmessageList\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x05\x12\"\n\x07message\x18\x02 \x03(\x0b\x32\x11.topic.subMessage\"$\n\x0esubscriberInfo\x12\x12\n\ncategories\x18\x01 \x03(\x05\"\x07\n\x05\x65mpty2\x94\x01\n\x05topic\x12*\n\x07publish\x12\x11.topic.pubMessage\x1a\n.topic.ack\"\x00\x12\x38\n\tsubscribe\x12\x15.topic.subscriberInfo\x1a\x12.topic.messageList\"\x00\x12%\n\x07sub_ack\x12\n.topic.ack\x1a\x0c.topic.empty\"\x00'
)




_ACK = _descriptor.Descriptor(
  name='ack',
  full_name='topic.ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='topic.ack.ack', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=40,
)


_PUBMESSAGE = _descriptor.Descriptor(
  name='pubMessage',
  full_name='topic.pubMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='topic.pubMessage.category', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeoutLimit', full_name='topic.pubMessage.timeoutLimit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='topic.pubMessage.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=111,
)


_SUBMESSAGE = _descriptor.Descriptor(
  name='subMessage',
  full_name='topic.subMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='topic.subMessage.category', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='topic.subMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=160,
)


_MESSAGELIST = _descriptor.Descriptor(
  name='messageList',
  full_name='topic.messageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='topic.messageList.ack', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='topic.messageList.message', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=224,
)


_SUBSCRIBERINFO = _descriptor.Descriptor(
  name='subscriberInfo',
  full_name='topic.subscriberInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='categories', full_name='topic.subscriberInfo.categories', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=262,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='topic.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=271,
)

_MESSAGELIST.fields_by_name['message'].message_type = _SUBMESSAGE
DESCRIPTOR.message_types_by_name['ack'] = _ACK
DESCRIPTOR.message_types_by_name['pubMessage'] = _PUBMESSAGE
DESCRIPTOR.message_types_by_name['subMessage'] = _SUBMESSAGE
DESCRIPTOR.message_types_by_name['messageList'] = _MESSAGELIST
DESCRIPTOR.message_types_by_name['subscriberInfo'] = _SUBSCRIBERINFO
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.ack)
  })
_sym_db.RegisterMessage(ack)

pubMessage = _reflection.GeneratedProtocolMessageType('pubMessage', (_message.Message,), {
  'DESCRIPTOR' : _PUBMESSAGE,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.pubMessage)
  })
_sym_db.RegisterMessage(pubMessage)

subMessage = _reflection.GeneratedProtocolMessageType('subMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBMESSAGE,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.subMessage)
  })
_sym_db.RegisterMessage(subMessage)

messageList = _reflection.GeneratedProtocolMessageType('messageList', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGELIST,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.messageList)
  })
_sym_db.RegisterMessage(messageList)

subscriberInfo = _reflection.GeneratedProtocolMessageType('subscriberInfo', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERINFO,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.subscriberInfo)
  })
_sym_db.RegisterMessage(subscriberInfo)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:topic.empty)
  })
_sym_db.RegisterMessage(empty)



_TOPIC = _descriptor.ServiceDescriptor(
  name='topic',
  full_name='topic.topic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=274,
  serialized_end=422,
  methods=[
  _descriptor.MethodDescriptor(
    name='publish',
    full_name='topic.topic.publish',
    index=0,
    containing_service=None,
    input_type=_PUBMESSAGE,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='topic.topic.subscribe',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBERINFO,
    output_type=_MESSAGELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sub_ack',
    full_name='topic.topic.sub_ack',
    index=2,
    containing_service=None,
    input_type=_ACK,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPIC)

DESCRIPTOR.services_by_name['topic'] = _TOPIC

# @@protoc_insertion_point(module_scope)
